services:
  vhost:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-embarcados:/data/db

  gateway:
    build: ./gateway
    environment:
      CLIENTS_URL: "http://clients:5000"
      VIRTUAL_HOST: "api.127.0.0.1.nip.io"

  clients:
    build: ./services/clients
    environment:
      MONGODB_URL: "mongodb://mongodb:27017"
      VIRTUAL_HOST: "clients.127.0.0.1.nip.io"
    depends_on:
      - mongodb

volumes:
  data-embarcados:
